export const sampleEquipment = [
  {
    id: 1,
    name: 'Excavator CAT 320',
    category: 'Heavy Equipment',
    serialNumber: 'CAT-320-001',
    status: 'assigned',
    project: 'Downtown Bridge Project',
    condition: 'good',
    quantity: 1,
    purchaseDate: '2021-06-15',
    maintenanceDate: '2026-09-20',
    location: 'Site A',
    assignedTo: 'John Smith',
    notes: 'Recently serviced and ready for excavation work.',
  },
  {
    id: 2,
    name: 'Concrete Mixer',
    category: 'Tools',
    serialNumber: 'MIX-203-016',
    status: 'available',
    project: '',
    condition: 'good',
    quantity: 2,
    purchaseDate: '2023-03-10',
    maintenanceDate: '2026-08-15',
    location: 'Warehouse A',
    assignedTo: '',
    notes: 'Specifically used for concrete pours and site support.',
  },
  {
    id: 3,
    name: 'Scaffolding Kit',
    category: 'Safety Equipment',
    serialNumber: 'SCAF-902-01',
    status: 'maintenance',
    project: 'Mall Expansion',
    condition: 'fair',
    quantity: 5,
    purchaseDate: '2020-01-20',
    maintenanceDate: '2026-10-10',
    location: 'Storage Yard',
    assignedTo: 'Safety Team',
    notes: 'Inspection due before next deployment.',
  },
  {
    id: 4,
    name: 'Jackhammer RH-7',
    category: 'Power Tools',
    serialNumber: 'JH-7-910',
    status: 'broken',
    project: '',
    condition: 'poor',
    quantity: 1,
    purchaseDate: '2019-11-11',
    maintenanceDate: '2025-12-01',
    location: 'Workshop',
    assignedTo: '',
    notes: 'Motor needs replacement and inspection by mechanic.',
  }
]
